name = "leaders-meetup-bot"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "leaders-meetup-bot"
database_id = "417d85e1-611e-4fff-a72c-d5b0f98761ac"

[triggers]
crons = ["*/5 * * * *"]

[assets]
directory = "./public"
