name = "leaders-meetup-bot"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# [[d1_databases]]
# binding = "DB"
# database_name = "leaders-meetup-bot"
# database_id = "xxxxxxxx"

# [triggers]
# crons = ["*/5 * * * *"]
