import type { CSSProperties } from "react";
import { colors } from "../../styles/tokens";

// Phase4-4: EmailTemplatesEditor.tsx から純抽出した style 定義。
// 値・キー・順序は一字一句不変。EmailTemplatesEditor 本体と
// LogToSlackSection の両方が参照する共有 style。

export const styles = {
  container: { padding: "1rem" } as CSSProperties,
  description: {
    color: colors.textSecondary,
    fontSize: "0.875rem",
    marginTop: 0,
    marginBottom: "0.5rem",
  } as CSSProperties,
  helpBox: {
    background: colors.surface,
    border: `1px solid ${colors.border}`,
    borderRadius: "0.375rem",
    padding: "0.5rem 0.75rem",
    fontSize: "0.8125rem",
    marginBottom: "1rem",
  } as CSSProperties,
  helpHint: {
    color: colors.textSecondary,
    fontSize: "0.75rem",
    marginTop: "0.25rem",
  } as CSSProperties,
  error: {
    color: colors.danger,
    background: colors.dangerSubtle,
    border: `1px solid ${colors.dangerSubtle}`,
    borderRadius: "0.25rem",
    padding: "0.5rem 0.75rem",
    marginBottom: "0.75rem",
    fontSize: "0.875rem",
  } as CSSProperties,
  empty: {
    padding: "1.5rem",
    textAlign: "center",
    color: colors.textSecondary,
    border: `1px dashed ${colors.borderStrong}`,
    borderRadius: "0.5rem",
    marginBottom: "0.75rem",
  } as CSSProperties,
  card: {
    border: `1px solid ${colors.border}`,
    borderRadius: "0.375rem",
    padding: "0.75rem",
    background: colors.background,
  } as CSSProperties,
  cardHeader: {
    display: "flex",
    gap: "0.5rem",
    alignItems: "center",
    marginBottom: "0.5rem",
  } as CSSProperties,
  cardActions: {
    display: "flex",
    gap: "0.25rem",
    flexShrink: 0,
  } as CSSProperties,
  nameInput: {
    flex: 1,
    padding: "0.375rem 0.5rem",
    border: `1px solid ${colors.borderStrong}`,
    borderRadius: "0.25rem",
    fontSize: "0.875rem",
  } as CSSProperties,
  subjectInput: {
    width: "100%",
    padding: "0.375rem 0.5rem",
    border: `1px solid ${colors.borderStrong}`,
    borderRadius: "0.25rem",
    fontSize: "0.8125rem",
    marginBottom: "0.5rem",
    boxSizing: "border-box",
  } as CSSProperties,
  autoSendBox: {
    background: colors.surface,
    border: `1px solid ${colors.border}`,
    borderRadius: "0.375rem",
    padding: "0.75rem 1rem",
    marginBottom: "1rem",
  } as CSSProperties,
  autoSendHeader: {
    display: "flex",
    alignItems: "center",
    gap: "0.75rem",
    marginBottom: "0.25rem",
  } as CSSProperties,
  toggleLabel: {
    marginLeft: "auto",
    display: "flex",
    alignItems: "center",
    gap: "0.25rem",
    fontSize: "0.875rem",
    cursor: "pointer",
  } as CSSProperties,
  autoSendRow: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    marginTop: "0.5rem",
  } as CSSProperties,
  autoSendLabel: {
    minWidth: "9rem",
    fontSize: "0.8125rem",
    color: colors.textSecondary,
  } as CSSProperties,
  triggersGroup: {
    marginTop: "0.75rem",
    paddingTop: "0.5rem",
    borderTop: `1px dashed ${colors.border}`,
  } as CSSProperties,
  triggersTitle: {
    fontSize: "0.8125rem",
    fontWeight: 600,
    color: colors.textSecondary,
    marginBottom: "0.25rem",
  } as CSSProperties,
  triggerRow: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    marginTop: "0.5rem",
  } as CSSProperties,
  triggerLabelBlock: {
    minWidth: "11rem",
    display: "flex",
    flexDirection: "column",
  } as CSSProperties,
  triggerLabel: {
    fontSize: "0.875rem",
    fontWeight: 500,
  } as CSSProperties,
  triggerDescription: {
    fontSize: "0.6875rem",
    color: colors.textSecondary,
    marginTop: "0.125rem",
  } as CSSProperties,
  select: {
    flex: 1,
    padding: "0.375rem 0.5rem",
    border: `1px solid ${colors.borderStrong}`,
    borderRadius: "0.25rem",
    fontSize: "0.875rem",
    background: colors.background,
  } as CSSProperties,
  bodyArea: {
    width: "100%",
    padding: "0.5rem",
    border: `1px solid ${colors.borderStrong}`,
    borderRadius: "0.25rem",
    fontFamily: "monospace",
    fontSize: "0.8125rem",
    resize: "vertical",
    boxSizing: "border-box",
  } as CSSProperties,
  iconBtn: {
    width: "2rem",
    height: "2rem",
    border: `1px solid ${colors.borderStrong}`,
    background: colors.background,
    borderRadius: "0.25rem",
    cursor: "pointer",
    fontSize: "0.875rem",
  } as CSSProperties,
  deleteIconBtn: {
    color: colors.danger,
    borderColor: colors.dangerSubtle,
  } as CSSProperties,
  buttonRow: {
    display: "flex",
    gap: "0.5rem",
    marginTop: "1rem",
    alignItems: "center",
    flexWrap: "wrap",
  } as CSSProperties,
  secondaryBtn: {
    padding: "0.5rem 1rem",
    border: `1px solid ${colors.borderStrong}`,
    background: colors.background,
    borderRadius: "0.375rem",
    cursor: "pointer",
    fontSize: "0.875rem",
  } as CSSProperties,
  primaryBtn: {
    padding: "0.5rem 1.5rem",
    background: colors.primary,
    color: colors.textInverse,
    border: "none",
    borderRadius: "0.375rem",
    cursor: "pointer",
    fontSize: "0.875rem",
  } as CSSProperties,
  slackInviteToggle: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    padding: 0,
    background: "transparent",
    border: "none",
    cursor: "pointer",
    textAlign: "left",
    fontSize: "0.875rem",
    color: colors.text,
  } as CSSProperties,
  slackInviteToggleArrow: {
    color: colors.textSecondary,
    width: "1rem",
  } as CSSProperties,
  slackInviteSummary: {
    marginLeft: "auto",
    color: colors.textSecondary,
    fontSize: "0.75rem",
    fontWeight: 400,
  } as CSSProperties,
  mentionList: {
    border: `1px solid ${colors.border}`,
    borderRadius: "0.25rem",
    padding: "0.5rem",
    maxHeight: "240px",
    overflowY: "auto",
    background: colors.background,
  } as CSSProperties,
  mentionRow: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    padding: "0.25rem 0.5rem",
    cursor: "pointer",
    fontSize: "0.875rem",
  } as CSSProperties,
  noticeBox: {
    marginTop: "0.75rem",
    padding: "0.5rem 0.75rem",
    background: colors.warningSubtle,
    border: `1px solid ${colors.warning}`,
    borderRadius: "0.25rem",
    fontSize: "0.75rem",
    color: colors.text,
    lineHeight: 1.5,
  } as CSSProperties,
  summaryList: {
    margin: "0.5rem 0 0",
    paddingLeft: "1.25rem",
    fontSize: "0.8125rem",
  } as CSSProperties,
  summaryItem: {
    marginBottom: "0.25rem",
    color: colors.text,
  } as CSSProperties,
  summaryUrl: {
    color: colors.textSecondary,
    wordBreak: "break-all",
    fontFamily: "monospace",
    fontSize: "0.75rem",
  } as CSSProperties,
  inviteCard: {
    border: `1px solid ${colors.border}`,
    borderRadius: "0.375rem",
    padding: "0.75rem",
    background: colors.background,
    marginTop: "0.5rem",
  } as CSSProperties,
  inviteCardHeader: {
    display: "flex",
    gap: "0.5rem",
    alignItems: "center",
    marginBottom: "0.5rem",
  } as CSSProperties,
  // === LogToSlackSection 用スタイル ===
  logRow: {
    marginTop: "0.5rem",
  } as CSSProperties,
  summaryRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "0.75rem",
    padding: "0.5rem 0.75rem",
    border: `1px solid ${colors.border}`,
    borderRadius: "0.25rem",
    background: colors.background,
  } as CSSProperties,
  summaryBody: {
    flex: 1,
    minWidth: 0,
  } as CSSProperties,
  summaryLabel: {
    fontSize: "0.75rem",
    color: colors.textSecondary,
    marginBottom: "0.125rem",
  } as CSSProperties,
  summaryValue: {
    fontSize: "0.875rem",
    color: colors.text,
    wordBreak: "break-word",
  } as CSSProperties,
  editBox: {
    padding: "0.75rem",
    border: `1px solid ${colors.borderStrong}`,
    borderRadius: "0.25rem",
    background: colors.background,
  } as CSSProperties,
  editTitle: {
    fontSize: "0.875rem",
    fontWeight: 600,
    marginBottom: "0.5rem",
  } as CSSProperties,
  editActions: {
    display: "flex",
    gap: "0.5rem",
    marginTop: "0.5rem",
    flexWrap: "wrap",
  } as CSSProperties,
  templatePreview: {
    margin: 0,
    padding: "0.5rem 0.75rem",
    border: `1px solid ${colors.border}`,
    borderRadius: "0.25rem",
    background: colors.surface,
    fontSize: "0.8125rem",
    color: colors.text,
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  } as CSSProperties,
  placeholderList: {
    display: "grid",
    gridTemplateColumns: "auto 1fr",
    columnGap: "0.5rem",
    rowGap: "0.125rem",
    padding: "0.5rem",
    border: `1px solid ${colors.border}`,
    borderRadius: "0.25rem",
    background: colors.surface,
    fontSize: "0.75rem",
    margin: "0.5rem 0",
  } as CSSProperties,
  placeholderRow: {
    display: "contents",
  } as CSSProperties,
  placeholderKey: {
    color: colors.text,
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
  } as CSSProperties,
  placeholderDesc: {
    color: colors.textSecondary,
  } as CSSProperties,
};
